### ISSUE TITLE
Input field is not cleared if a digit is clicked after the "equal" operator

### ISSUE THREAD

**Issue by chapluck** [saxarkompot/js-junior#2]
Steps to reproduce:
1. Input a number "44"
2. Click "plus".
3. Input a number "11"
4. Click "equal".
5. Value "55" appears in the input textbox.
6. Click any digit.

Actual result:
The digit is added to the value in the input. For example: 556

Expected result: 
The input filed is cleared and only the digit is presented in the input. For example: 6

**Comment by saxarkompot** [comment]
Ok. Budem robit'

**Comment by saxarkompot** [comment]
))

**Comment by saxarkompot** [comment]
Task completed.
I have a question:
- I enter a number (for example, "1")
- click "+"
- I enter the number "5"
- clicked "="
- the number "6" is displayed
- clicked "=" again
- "7" is displayed and so on
As a result, the number "1" priority is the first, but I need the second number

**Comment by chapluck** [comment]
This is an excellent observation! Fix it!

**Comment by saxarkompot** [comment]
Added 4 buttons.
Created comments in the code.
Fixed a bug with the calculation operations.
